name: Build and Deploy
on: [push]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd:
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build