name: Test Build
on: [pull_request]
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      - name: Run yarn
        run: yarn
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build